auto: true

markdown: rdiscount

highlighter: 'pygments'
#paginate: 8
permalink: /:title

name: “madpig's Blog”
title: madpig's blog
description: Everything about madpig.
url: http://xiaolangren.github.io
feed: /atom.xml
author_info: <a href="http://xiaolangren.github.io/">madpig</a>
